export const tier1Cards = [
	{gem: "onyx", tier: 1, points: 1, cost: {sapphire: 4}},
	{gem: "onyx", tier: 1, points: 0, cost: {emerald: 3}},
	{gem: "onyx", tier: 1, points: 0, cost: {emerald: 2, ruby: 1}},
	{gem: "onyx", tier: 1, points: 0, cost: {emerald: 1, ruby: 3, onyx: 1}},
	{gem: "onyx", tier: 1, points: 0, cost: {diamond: 1, sapphire: 2, emerald: 1, ruby: 1}},
	{gem: "onyx", tier: 1, points: 0, cost: {diamond: 1, sapphire: 1, emerald: 1, ruby: 1}},
	{gem: "onyx", tier: 1, points: 0, cost: {diamond: 2, sapphire: 2, ruby: 1}},
	{gem: "onyx", tier: 1, points: 0, cost: {diamond: 2, emerald: 2}},
	{gem: "sapphire", tier: 1, points: 0, cost: {onyx: 3}},
	{gem: "sapphire", tier: 1, points: 0, cost: {sapphire: 1, emerald: 3, ruby: 1}},
	{gem: "sapphire", tier: 1, points: 0, cost: {emerald: 2, onyx: 2}},
	{gem: "sapphire", tier: 1, points: 1, cost: {ruby: 4}},
	{gem: "sapphire", tier: 1, points: 0, cost: {diamond: 1, onyx: 2}},
	{gem: "sapphire", tier: 1, points: 0, cost: {diamond: 1, emerald: 2, ruby: 2}},
	{gem: "sapphire", tier: 1, points: 0, cost: {diamond: 1, emerald: 1, ruby: 1, onyx: 1}},
	{gem: "sapphire", tier: 1, points: 0, cost: {diamond: 1, emerald: 1, ruby: 2, onyx: 1}},
	{gem: "emerald", tier: 1, points: 1, cost: {onyx: 4}},
	{gem: "emerald", tier: 1, points: 0, cost: {sapphire: 2, ruby: 2}},
	{gem: "emerald", tier: 1, points: 0, cost: {sapphire: 1, ruby: 2, onyx: 2}},
	{gem: "emerald", tier: 1, points: 0, cost: {ruby: 3}},
	{gem: "emerald", tier: 1, points: 0, cost: {diamond: 1, sapphire: 3, emerald: 1}},
	{gem: "emerald", tier: 1, points: 0, cost: {diamond: 1, sapphire: 1, ruby: 1, onyx: 2}},
	{gem: "emerald", tier: 1, points: 0, cost: {diamond: 1, sapphire: 1, ruby: 1, onyx: 1}},
	{gem: "emerald", tier: 1, points: 0, cost: {diamond: 2, sapphire: 1}},
	{gem: "ruby", tier: 1, points: 0, cost: {sapphire: 2, emerald: 1}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 1, sapphire: 1, emerald: 1, onyx: 1}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 1, ruby: 1, onyx: 3}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 2, sapphire: 1, emerald: 1, onyx: 1}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 2, emerald: 1, onyx: 2}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 2, ruby: 2}},
	{gem: "ruby", tier: 1, points: 1, cost: {diamond: 4}},
	{gem: "ruby", tier: 1, points: 0, cost: {diamond: 3}},
	{gem: "diamond", tier: 1, points: 0, cost: {sapphire: 2, onyx: 2}},
	{gem: "diamond", tier: 1, points: 0, cost: {sapphire: 3}},
	{gem: "diamond", tier: 1, points: 0, cost: {sapphire: 2, emerald: 2, onyx: 1}},
	{gem: "diamond", tier: 1, points: 0, cost: {sapphire: 1, emerald: 2, ruby: 1, onyx: 1}},
	{gem: "diamond", tier: 1, points: 0, cost: {sapphire: 1, emerald: 1, ruby: 1, onyx: 1}},
	{gem: "diamond", tier: 1, points: 1, cost: {emerald: 4}},
	{gem: "diamond", tier: 1, points: 0, cost: {ruby: 2, onyx: 1}},
	{gem: "diamond", tier: 1, points: 0, cost: {diamond: 3, sapphire: 1, onyx: 1}},
]
export const tier2Cards = [
	{gem: "onyx", tier: 2, points: 3, cost: {onyx: 6}},
	{gem: "onyx", tier: 2, points: 2, cost: {onyx: 5}},
	{gem: "onyx", tier: 2, points: 2, cost: {sapphire: 1, emerald: 4, ruby: 2}},
	{gem: "onyx", tier: 2, points: 2, cost: {emerald: 5, ruby: 3}},
	{gem: "onyx", tier: 2, points: 1, cost: {diamond: 3, sapphire: 2, emerald: 2}},
	{gem: "onyx", tier: 2, points: 1, cost: {diamond: 3, emerald: 3, onyx: 2}},
	{gem: "sapphire", tier: 2, points: 3, cost: {sapphire: 6}},
	{gem: "sapphire", tier: 2, points: 2, cost: {sapphire: 5}},
	{gem: "sapphire", tier: 2, points: 1, cost: {sapphire: 2, emerald: 2, ruby: 3}},
	{gem: "sapphire", tier: 2, points: 2, cost: {diamond: 2, ruby: 1, onyx: 4}},
	{gem: "sapphire", tier: 2, points: 2, cost: {diamond: 5, sapphire: 3}},
	{gem: "emerald", tier: 2, points: 2, cost: {sapphire: 5, emerald: 3}},
	{gem: "emerald", tier: 2, points: 3, cost: {emerald: 6}},
	{gem: "emerald", tier: 2, points: 2, cost: {emerald: 5}},
	{gem: "emerald", tier: 2, points: 1, cost: {diamond: 2, sapphire: 3, onyx: 2}},
	{gem: "emerald", tier: 2, points: 1, cost: {diamond: 3, emerald: 2, ruby: 2}},
	{gem: "emerald", tier: 2, points: 2, cost: {diamond: 4, sapphire: 2, onyx: 1}},
	{gem: "ruby", tier: 2, points: 2, cost: {onyx: 5}},
	{gem: "ruby", tier: 2, points: 1, cost: {sapphire: 3, ruby: 2, onyx: 3}},
	{gem: "ruby", tier: 2, points: 3, cost: {ruby: 6}},
	{gem: "ruby", tier: 2, points: 2, cost: {diamond: 1, sapphire: 4, emerald: 2}},
	{gem: "ruby", tier: 2, points: 1, cost: {diamond: 2, ruby: 2, onyx: 3}},
	{gem: "ruby", tier: 2, points: 2, cost: {diamond: 3, onyx: 5}},
	{gem: "diamond", tier: 2, points: 1, cost: {emerald: 3, ruby: 2, onyx: 2}},
	{gem: "diamond", tier: 2, points: 2, cost: {emerald: 1, ruby: 4, onyx: 2}},
	{gem: "diamond", tier: 2, points: 2, cost: {ruby: 5, onyx: 3}},
	{gem: "diamond", tier: 2, points: 2, cost: {ruby: 5}},
	{gem: "diamond", tier: 2, points: 1, cost: {diamond: 2, sapphire: 3, ruby: 3}},
	{gem: "diamond", tier: 2, points: 3, cost: {diamond: 6}},
]
export const tier3Cards = [
	{gem: "diamond", tier: 3, points: 4, cost: {onyx: 7}},
	{gem: "diamond", tier: 3, points: 5, cost: {diamond: 3, onyx: 7}},
	{gem: "diamond", tier: 3, points: 4, cost: {diamond: 3, ruby: 3, onyx: 6}},
	{gem: "diamond", tier: 3, points: 3, cost: {sapphire: 3, emerald: 3, ruby: 5, onyx: 3}},
	{gem: "sapphire", tier: 3, points: 4, cost: {diamond: 7}},
	{gem: "sapphire", tier: 3, points: 5, cost: {diamond: 7, sapphire: 3}},
	{gem: "sapphire", tier: 3, points: 4, cost: {diamond: 6, sapphire: 3, onyx: 3}},
	{gem: "sapphire", tier: 3, points: 3, cost: {diamond: 3, emerald: 3, ruby: 3, onyx: 5}},
	{gem: "emerald", tier: 3, points: 4, cost: {sapphire: 7}},
	{gem: "emerald", tier: 3, points: 5, cost: {sapphire: 7, emerald: 3}},
	{gem: "emerald", tier: 3, points: 4, cost: {diamond: 3, sapphire: 6, emerald: 3}},
	{gem: "emerald", tier: 3, points: 3, cost: {diamond: 5, sapphire: 3, ruby: 3, onyx: 3}},
	{gem: "ruby", tier: 3, points: 4, cost: {emerald: 7}},
	{gem: "ruby", tier: 3, points: 5, cost: {emerald: 7, ruby: 3}},
	{gem: "ruby", tier: 3, points: 4, cost: {sapphire: 3, emerald: 6, ruby: 3}},
	{gem: "ruby", tier: 3, points: 3, cost: {diamond: 3, sapphire: 5, emerald: 3, onyx: 3}},
	{gem: "onyx", tier: 3, points: 4, cost: {ruby: 7}},
	{gem: "onyx", tier: 3, points: 5, cost: {ruby: 7, onyx: 3}},
	{gem: "onyx", tier: 3, points: 4, cost: {emerald: 3, ruby: 6, onyx: 3}},
	{gem: "onyx", tier: 3, points: 3, cost: {diamond: 3, sapphire: 3, emerald: 5, ruby: 3}}
]

export const nobles = [
	{cost: {emerald: 3, sapphire: 3, ruby: 3}},
	{cost: {emerald: 3, sapphire: 3, diamond: 3}},
	{cost: {onyx: 3, ruby: 3, emerald: 3}},
	{cost: {onyx: 3, ruby: 3, diamond: 3}},
	{cost: {onyx: 3, sapphire: 3, diamond: 3}},
	{cost: {sapphire: 4, emerald: 4}},
	{cost: {onyx: 4, diamond: 4}},
	{cost: {ruby: 4, emerald: 4}},
	{cost: {onyx: 4, ruby: 4}},
	{cost: {sapphire: 4, diamond: 4}}
]