import Bundle from "./bundle.js"

export const tier1Cards = [
	{gem: "onyx", tier: 1, points: 1, cost: new Bundle({sapphire: 4})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({emerald: 3})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({emerald: 2, ruby: 1})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({emerald: 1, ruby: 3, onyx: 1})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 2, emerald: 1, ruby: 1})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 1, emerald: 1, ruby: 1})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({diamond: 2, sapphire: 2, ruby: 1})},
	{gem: "onyx", tier: 1, points: 0, cost: new Bundle({diamond: 2, emerald: 2})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({onyx: 3})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({sapphire: 1, emerald: 3, ruby: 1})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({emerald: 2, onyx: 2})},
	{gem: "sapphire", tier: 1, points: 1, cost: new Bundle({ruby: 4})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({diamond: 1, onyx: 2})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({diamond: 1, emerald: 2, ruby: 2})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({diamond: 1, emerald: 1, ruby: 1, onyx: 1})},
	{gem: "sapphire", tier: 1, points: 0, cost: new Bundle({diamond: 1, emerald: 1, ruby: 2, onyx: 1})},
	{gem: "emerald", tier: 1, points: 1, cost: new Bundle({onyx: 4})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({sapphire: 2, ruby: 2})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({sapphire: 1, ruby: 2, onyx: 2})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({ruby: 3})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 3, emerald: 1})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 1, ruby: 1, onyx: 2})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 1, ruby: 1, onyx: 1})},
	{gem: "emerald", tier: 1, points: 0, cost: new Bundle({diamond: 2, sapphire: 1})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({sapphire: 2, emerald: 1})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 1, sapphire: 1, emerald: 1, onyx: 1})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 1, ruby: 1, onyx: 3})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 2, sapphire: 1, emerald: 1, onyx: 1})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 2, emerald: 1, onyx: 2})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 2, ruby: 2})},
	{gem: "ruby", tier: 1, points: 1, cost: new Bundle({diamond: 4})},
	{gem: "ruby", tier: 1, points: 0, cost: new Bundle({diamond: 3})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({sapphire: 2, onyx: 2})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({sapphire: 3})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({sapphire: 2, emerald: 2, onyx: 1})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({sapphire: 1, emerald: 2, ruby: 1, onyx: 1})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({sapphire: 1, emerald: 1, ruby: 1, onyx: 1})},
	{gem: "diamond", tier: 1, points: 1, cost: new Bundle({emerald: 4})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({ruby: 2, onyx: 1})},
	{gem: "diamond", tier: 1, points: 0, cost: new Bundle({diamond: 3, sapphire: 1, onyx: 1})},
]
export const tier2Cards = [
	{gem: "onyx", tier: 2, points: 3, cost: new Bundle({onyx: 6})},
	{gem: "onyx", tier: 2, points: 2, cost: new Bundle({onyx: 5})},
	{gem: "onyx", tier: 2, points: 2, cost: new Bundle({sapphire: 1, emerald: 4, ruby: 2})},
	{gem: "onyx", tier: 2, points: 2, cost: new Bundle({emerald: 5, ruby: 3})},
	{gem: "onyx", tier: 2, points: 1, cost: new Bundle({diamond: 3, sapphire: 2, emerald: 2})},
	{gem: "onyx", tier: 2, points: 1, cost: new Bundle({diamond: 3, emerald: 3, onyx: 2})},
	{gem: "sapphire", tier: 2, points: 3, cost: new Bundle({sapphire: 6})},
	{gem: "sapphire", tier: 2, points: 2, cost: new Bundle({sapphire: 5})},
	{gem: "sapphire", tier: 2, points: 1, cost: new Bundle({sapphire: 2, emerald: 2, ruby: 3})},
	{gem: "sapphire", tier: 2, points: 2, cost: new Bundle({diamond: 2, ruby: 1, onyx: 4})},
	{gem: "sapphire", tier: 2, points: 2, cost: new Bundle({diamond: 5, sapphire: 3})},
	{gem: "emerald", tier: 2, points: 2, cost: new Bundle({sapphire: 5, emerald: 3})},
	{gem: "emerald", tier: 2, points: 3, cost: new Bundle({emerald: 6})},
	{gem: "emerald", tier: 2, points: 2, cost: new Bundle({emerald: 5})},
	{gem: "emerald", tier: 2, points: 1, cost: new Bundle({diamond: 2, sapphire: 3, onyx: 2})},
	{gem: "emerald", tier: 2, points: 1, cost: new Bundle({diamond: 3, emerald: 2, ruby: 2})},
	{gem: "emerald", tier: 2, points: 2, cost: new Bundle({diamond: 4, sapphire: 2, onyx: 1})},
	{gem: "ruby", tier: 2, points: 2, cost: new Bundle({onyx: 5})},
	{gem: "ruby", tier: 2, points: 1, cost: new Bundle({sapphire: 3, ruby: 2, onyx: 3})},
	{gem: "ruby", tier: 2, points: 3, cost: new Bundle({ruby: 6})},
	{gem: "ruby", tier: 2, points: 2, cost: new Bundle({diamond: 1, sapphire: 4, emerald: 2})},
	{gem: "ruby", tier: 2, points: 1, cost: new Bundle({diamond: 2, ruby: 2, onyx: 3})},
	{gem: "ruby", tier: 2, points: 2, cost: new Bundle({diamond: 3, onyx: 5})},
	{gem: "diamond", tier: 2, points: 1, cost: new Bundle({emerald: 3, ruby: 2, onyx: 2})},
	{gem: "diamond", tier: 2, points: 2, cost: new Bundle({emerald: 1, ruby: 4, onyx: 2})},
	{gem: "diamond", tier: 2, points: 2, cost: new Bundle({ruby: 5, onyx: 3})},
	{gem: "diamond", tier: 2, points: 2, cost: new Bundle({ruby: 5})},
	{gem: "diamond", tier: 2, points: 1, cost: new Bundle({diamond: 2, sapphire: 3, ruby: 3})},
	{gem: "diamond", tier: 2, points: 3, cost: new Bundle({diamond: 6})},
]
export const tier3Cards = [
	{gem: "diamond", tier: 3, points: 4, cost: new Bundle({onyx: 7})},
	{gem: "diamond", tier: 3, points: 5, cost: new Bundle({diamond: 3, onyx: 7})},
	{gem: "diamond", tier: 3, points: 4, cost: new Bundle({diamond: 3, ruby: 3, onyx: 6})},
	{gem: "diamond", tier: 3, points: 3, cost: new Bundle({sapphire: 3, emerald: 3, ruby: 5, onyx: 3})},
	{gem: "sapphire", tier: 3, points: 4, cost: new Bundle({diamond: 7})},
	{gem: "sapphire", tier: 3, points: 5, cost: new Bundle({diamond: 7, sapphire: 3})},
	{gem: "sapphire", tier: 3, points: 4, cost: new Bundle({diamond: 6, sapphire: 3, onyx: 3})},
	{gem: "sapphire", tier: 3, points: 3, cost: new Bundle({diamond: 3, emerald: 3, ruby: 3, onyx: 5})},
	{gem: "emerald", tier: 3, points: 4, cost: new Bundle({sapphire: 7})},
	{gem: "emerald", tier: 3, points: 5, cost: new Bundle({sapphire: 7, emerald: 3})},
	{gem: "emerald", tier: 3, points: 4, cost: new Bundle({diamond: 3, sapphire: 6, emerald: 3})},
	{gem: "emerald", tier: 3, points: 3, cost: new Bundle({diamond: 5, sapphire: 3, ruby: 3, onyx: 3})},
	{gem: "ruby", tier: 3, points: 4, cost: new Bundle({emerald: 7})},
	{gem: "ruby", tier: 3, points: 5, cost: new Bundle({emerald: 7, ruby: 3})},
	{gem: "ruby", tier: 3, points: 4, cost: new Bundle({sapphire: 3, emerald: 6, ruby: 3})},
	{gem: "ruby", tier: 3, points: 3, cost: new Bundle({diamond: 3, sapphire: 5, emerald: 3, onyx: 3})},
	{gem: "onyx", tier: 3, points: 4, cost: new Bundle({ruby: 7})},
	{gem: "onyx", tier: 3, points: 5, cost: new Bundle({ruby: 7, onyx: 3})},
	{gem: "onyx", tier: 3, points: 4, cost: new Bundle({emerald: 3, ruby: 6, onyx: 3})},
	{gem: "onyx", tier: 3, points: 3, cost: new Bundle({diamond: 3, sapphire: 3, emerald: 5, ruby: 3})}
]

export const nobles = [
	{cost: new Bundle({emerald: 3, sapphire: 3, ruby: 3})},
	{cost: new Bundle({emerald: 3, sapphire: 3, diamond: 3})},
	{cost: new Bundle({onyx: 3, ruby: 3, emerald: 3})},
	{cost: new Bundle({onyx: 3, ruby: 3, diamond: 3})},
	{cost: new Bundle({onyx: 3, sapphire: 3, diamond: 3})},
	{cost: new Bundle({sapphire: 4, emerald: 4})},
	{cost: new Bundle({onyx: 4, diamond: 4})},
	{cost: new Bundle({ruby: 4, emerald: 4})},
	{cost: new Bundle({onyx: 4, ruby: 4})},
	{cost: new Bundle({sapphire: 4, diamond: 4})},
]